[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]


[package]
name = "pixi-build-api-version"
version = "1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
