# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: pixi-build-api-version
  version: "1"

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  noarch: generic

about:
  homepage: https://github.com/prefix-dev/pixi-build-backends
  summary: The protocol version for pixi build backends.
  description: |
    This package is used to define the API version of the protocol used by pixi build backends.
  license: BSD-3-Clause
  documentation: https://prefix-dev.github.io/pixi-build-backends
  repository: https://github.com/prefix-dev/pixi-build-backends
